### ISSUE TITLE
Debugging failure of check_program?

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/mni-perllib#1]
Hi,

I'm having issues with MNI perl-based scripts having trouble finding their programs (on SciNet).

Users seem to be able to run things like "mincresample" or "mincreshape" but if they try and use (for example) autocrop:

```
autocrop: couldn't find program "mincresample"
autocrop: couldn't find program "mincreshape"
Undefined subroutine &main::Fatal called at /project/m/mchakrav/quarantine/minc-toolkit/1.9.10/build/bin/autocrop line 188.
```

All of the MNI variables that the minc-toolkit environment script exports (PATH, etc) are being properly set, so I'm at a bit of a loss as to what's happening.

I'm not sure where to go debugging this, can you provide any insight?

Thanks.

Paging @andrewjanke

**Comment by vfonov** [comment]
Could it be an issue with passing environment variable to the jobs running in batch mode?

**Comment by gdevenyi** [comment]
This is without any batch stuff, just running on the command line.

**Comment by andrewjanke** [comment]
Hi Gabriel,

Does this error occur when the perl routine calls mincresample or is at the
"RegisterPrograms" stage during initialisation?

I have had RegisterPrograms fail for various strange reasons in the past
that were so difficult to track down that I gave up and commented the line
out. It does nothing functional than to die early if a script can't find
something that it will need later rather then dying when it needs it.

My guess is that Dave or Greg did this years ago because execution times
were long and they didn't want to waste CPU time.

These sorts of things with mni_perllib is what originally motivated me to
replace it with "do_cmd()" as I wasn't using much of its functionality
beyond Spawn().

a

**Comment by gdevenyi** [comment]
Currently, it's failing on the RegisterPrograms call, if I comment out the register call, I get this instead:

```
spawn: warning: program "mincreshape" not registered at /project/m/mchakrav/quarantine/minc-toolkit/1.9.10/build/bin/autocrop line 156
spawn: warning: couldn't find program "mincreshape"
autocrop: crashed while running mincreshape (termination status=65280)
```

**Comment by andrewjanke** [comment]
OK, so in this case it really can't find mincreshape (not just thinks it
can't).  The question is what is the value of path just before line 156 and
why. You are running autocrop local and not in a batch system?

And if so is /project/m/mchakrav/quarantine/minc-toolkit/1.9.10/build/bin/autocrop
where you expect to be getting autocrop from? and if so is mincreshape also
in that directory/path?

a

**Comment by gdevenyi** [comment]
> OK, so in this case it really can't find mincreshape (not just thinks it
> can't).  The question is what is the value of path just before line 156 and
> why. You are running autocrop local and not in a batch system?

Will check path values. 

Technically this is on a batch system, but I am intending to run locally.

> And if so is /project/m/mchakrav/quarantine/minc-toolkit/1.9.10/build/bin/autocrop
> where you expect to be getting autocrop from? and if so is mincreshape also
> in that directory/path?

Yes, that is correct. mincresample and mincreshape exist there _and_ I can run those commands directly in the same environment in which autocrop fails to find them

**Comment by gdevenyi** [comment]
> Will check path values.

Disturbingly, the paths are the same between a working user and a non-working user.

Your recommendation of `do_cmd` seems to have worked, I swapped it in for the Spawn call and it works. I guess for now we can do that.

**Comment by andrewjanke** [comment]
Ah, well now this is just getting far too interesting....

Time to diff the output of env for the two users. #!/usr/bin/perl or
#!/usr/bin/env perl?

Good to see you've solved it though.

a

**Comment by gdevenyi** [comment]
Good idea, will dump the ENV for both.

Latest minc-toolkit-v2 uses `#!/usr/bin/env perl`

Will have to continue tomorrow, user is gone home for the day and I don't have a environment I can replicate on my own... maybe I should just ask for her password....

**Comment by andrewjanke** [comment]
Ah, now we're getting somewhere. Check for a difference between .bashrc and
.bash_profile. They are sourced differently depending on the scheduler and
shell type (interactive or not).

a

**Comment by gdevenyi** [comment]
There is no difference between .bashrc and .bash_profile between the working user and the non-working user. :-/

**Comment by andrewjanke** [comment]
Well you've exhausted my (short) list of ideas then.

**Comment by gdevenyi** [comment]
Thanks for your help, I guess we'll handle it for now with the swap to use do_cmd.

**Comment by gdevenyi** [comment]
I found the root case of this, though I'm not sure this is fixable.

The permissions are being expressed via Linux ACL's and perl probably doesn't "get" those.

**Comment by gdevenyi** [comment]
I'm going to reopen here and ask a slightly different question.

How can I short-circuit the register/check program bits of the MNI perl libs so that things will "just work".

Lets presume I can guarantee that the programs needed are available.
